# Generated by Django 3.1.2 on 2020-11-01 00:51

import Tienda.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to=Tienda.models.PathAndRename('static/img/imgCategory/'))),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('precio', models.IntegerField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to=Tienda.models.PathAndRename('static/img/imgProductos/'))),
                ('tipoDeporte', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Tienda.deporte')),
            ],
        ),
    ]
